apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-python-app-ingress  
spec:
  rules:
  - host: powerbi.app.alrib.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-python-app-service
            port:
              number: 80
